# Generated by Django 3.1 on 2020-08-24 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('mobile', models.CharField(max_length=11, verbose_name='تلفن همراه')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='تصویر')),
                ('balance', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'مشتری ',
                'verbose_name_plural': 'مشتری',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50, verbose_name='نام کالا')),
                ('ProductPrice', models.IntegerField(verbose_name='قیمت')),
                ('ProductImage', models.ImageField(upload_to='product_images/', verbose_name='تصویر')),
                ('ProductStock', models.IntegerField(verbose_name='موجودی کالا')),
                ('ProductDescription', models.TextField(verbose_name='توضیح مخنصری در مورد کالا')),
                ('ProductStatus', models.IntegerField(choices=[(1, 'موجود در انبار'), (0, 'موجودی تا چند روز آینده')], verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالا',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ')),
                ('transaction_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان تراکنش')),
                ('transaction_code', models.CharField(max_length=30, verbose_name='رسید تراکنش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.customer', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت',
            },
        ),
        migrations.CreateModel(
            name='OrderApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_count', models.IntegerField(verbose_name='تعداد خرید')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.customer', verbose_name='خریدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سفارشات ',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
